theme: jekyll-theme-cayman
title: 飛行ロボットコンテスト ルール管理
description: 飛行ロボットコンテストのルールとレギュレーションを管理するリポジトリ（実験的プロジェクト）
lang: ja
show_downloads: false
google_analytics:

# Navbar Links
header_pages:
  - beginner/index.md
  - regular/index.md
  - images/index.md

# Custom data
contest_year: 2025
experimental: true
