site_name: "[テスト用] 飛行ロボットコンテスト ルール管理"
site_url: https://yaaasoh.github.io/flying-robot-contest-rules-public/
theme:
  name: material
  language: ja
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - navigation.sections
    - toc.integrate
    - search.highlight
  palette:
    primary: red
    accent: red

nav:
  - ホーム: index.md
  - 通常部門ルール: 20FlyRobo_ip_Regulations_text.md
  - ビギナー部門ルール: 20FlyRobo_Beginner_Regulations_text.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - tables
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
  - stylesheets/extra.css

plugins:
  - search
